version: '3.8'
services:
  api:
    container_name: api
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn dev
